apiVersion: v2
name: feedbox
description: A Helm chart for Kubernetes
type: application
version: 1.1.4
appVersion: "1.0.1"
keywords:
  - java
  - feedbox
  - oauth2
  - oidc
  - ingress
home: https://github.com/felixZmn/feedBox
