{{- if .Values.httpRoute.enabled -}}
{{- $svcName := include "feedbox.fullname" . -}}
{{- if .Values.oauth2Proxy.enabled -}}
{{- $svcName = printf "%s-oauth2-proxy" $svcName -}}
{{- end -}}
{{- $svcPort := ternary .Values.oauth2Proxy.service.port .Values.service.port .Values.oauth2Proxy.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "feedbox.fullname" . }}
  labels:
    {{- include "feedbox.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - name: {{ $svcName }}
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
{{- end }}
